#!/bin/sh

##Display Server
writeXServerConfig(){
    echo \ 
'#!/bin/sh
exec /usr/bin/Xorg -nolisten tcp "$@" vt$XDG_VTNR' 
}

sudo pacman -S xorg-xinit xorg-server

cp /etc/X11/xinit/xinitrc ~/.xinitrc
echo "exec bspwm" >> ~/.xinitrc

writeXServerConfig > ~/.xserverrc
