#!/bin/sh

## Display Server ##
writeXServerConfig(){
    echo \ 
'#!/bin/sh
exec /usr/bin/Xorg -nolisten tcp "$@" vt$XDG_VTNR' 
}

sudo pacman -S --noconfirm xorg-xinit xorg-server
cp /etc/X11/xinit/xinitrc ~/.xinitrc
echo "exec bspwm" >> ~/.xinitrc
writeXServerConfig > ~/.xserverrc

## Basic ##
sudo pacman -S --noconfirm base-devel git vim python rxvt-unicode kitty alacritty xclip feh ranger bspwm sxhkd picom mpd ncmpcpp

## dots  ##
git clone https://github.com/runtankrun/dotfiles.git
cp -rf $(find ~/dotfiles -maxdepth 2 -mindepth 2 | sed '/.*\(conky\|img\|doc\|git\).*/d') ~/

## Yay ##
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm

## Yay Packages ##
yay -S --noconfirm autojump fd mcfly fasd rg sd pywal rofi dunst cava neofech figlet wal eww dunst notify-send.sh ueberzug dmenu

## ZSH ##
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
yay -S --noconfirm git-open zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search
echo "##Plugins" >> ~/.zshrc
echo "source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc
echo "source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh" >> ~/.zshrc
echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc

## LibreWolf
yay -S librewolf-bin librewolf-extension-cookie-autodelete librewolf-ublock-origin librewolf-extension-localcdn
