#!/bin/sh

## Display Server ##
writeXServerConfig(){
    echo \ 
'#!/bin/sh
exec /usr/bin/Xorg -nolisten tcp "$@" vt$XDG_VTNR' 
}
sudo pacman -S --noconfirm xorg-xinit xorg-server
cp /etc/X11/xinit/xinitrc ~/.xinitrc
echo "exec bspwm" >> ~/.xinitrc
writeXServerConfig > ~/.xserverrc

## Basic ##
sudo pacman -S --noconfirm git vim python rxvt-unicode kitty feh ranger bspwm sxhkd picom mpd ncmpcpp feh

## Yay ##
sudo pacman -S --noconfirm --needed base-devel git
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

## Yay Packages ##
yay -S --noconfirm autojump fd mcfly fasd rg sd pywal rofi dunst cava neofech figlet 

## ZSH ##
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
yay -S --noconfirm git-open zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search 

## dots  ##
git clone https://github.com/runtankrun/dotfiles.git
