#!/bin/sh
dt=$(bspc query --desktops --names --desktop .\!occupied | head -n 1)
bspc desktop -f ^2:^$dt;

bspc node @^2:^$dt:/ -i 
bspc node @^2:^$dt:/ -o .5 -p east -i
bspc node @^2:^$dt:/1 -o .5 -p east -i
bspc node @^2:^$dt:/2 -o .5 -p east -i

bspc rule -a mpv:gl -o node=@^2:^$dt:/1/1
bspc rule -a mpv:gl -o node=@^2:^$dt:/1/2
bspc rule -a mpv:gl -o node=@^2:^$dt:/2/1
bspc rule -a mpv:gl -o node=@^2:^$dt:/2/2

rtags-quicklaunch -vid &
rtags-quicklaunch -vid &
rtags-quicklaunch -vid &
rtags-quicklaunch -vid
