#!/bin/sh
dt=$(bspc query --desktops --names --desktop .\!occupied | head -n 1)

##MOVE TO DESKTOP 
bspc desktop -f ^2:^$dt;

##INSERT RECEPTACLES
bspc node @^2:^$dt:/ -i
bspc node @^2:^$dt:/ -o 0.52 -p east -i
bspc node @^2:^$dt:/1 -o 0.52 -p south -i
bspc node @^2:^$dt:/2 -o 0.9 -p south -i

##ADD RULES
bspc rule -a URxvt:spot -o node=@^2:^$dt:/1/1
bspc rule -a Alacritty:music -o node=@^2:^$dt:/1/2
bspc rule -a URxvt:vis -o node=@^2:^$dt:/2/1
bspc rule -a URxvt:lofi -o node=@^2:^$dt:/2/2

##LAUNCH APPS
urxvtc -geometry 100x100 -name "spot" -title "spot" -e sh -c "spt;zsh" &
alacritty --title "music" --class "music" -e sh -c "~/.ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug" &
visualizer &
urxvtc -name "lofi" -title "lofi" -e sh -c 'mpv --x11-name="lofi" --title="lofi" ~/Music/ --mute=no --no-video;zsh' &
spotifyd -u chasetank -p $(pass spotify/spotifyd) -B 320
