#!/bin/sh

##KILL RECEPTACLES + CLOSE WINDOWS
while bspc node 'any.leaf.!window.!local' -k; do :; done;
while bspc node 'any.marked.!local' -c; do :; done;

##########
#   PS   #
##########
if [[ $1 = "-ps" ]]; then

##INSERT RECEPTACLES
bspc node @^1:^1:/ -i 
bspc node @^1:^1:/ -o .52 -p east -i
bspc node @^1:^1:/1 -o .498 -p south -i

##ADD RULES
bspc rule -a mpv:ps -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2 marked=on focus=off
bspc rule -a URxvt:tty-clock -o node=@^1:^1:/1/2 marked=on focus=off

##LAUNCH APPS
mpv --x11-name="ps" --title="ps" ~/Pictures/gifs/ps.GIF & 
c-gotop -kt &
urxvtc -name "tty-clock" -title "tty-clock" --transparent --color1 red -e sh -c "tty-clock -c -t -C 1" &

##FOCUS PRIMARY MONITOR
sleep .5s; bspc desktop --focus ^2:focused

################
#   VID-CASE   #
################
elif [[ $1 = "-vid" ]]; then

## VARIABLE
tag_count=$(grep -c ^C: ~/.config/ranger/tagged)

## INSERT RECEPTACLES
bspc node @^1:^1:/ -i
bspc node @^1:^1:/ -o 0.4575 -p east -i
bspc node @^1:^1:/1 -o 0.616719  -p south -i 
bspc node @^1:^1:/2 -o 0.385547 -p south -i

## ADD RULES
bspc rule -a URxvt:tty-clock -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a URxvt:vis-case -o node=@^1:^1:/1/2 marked=on focus=off
bspc rule -a mpv:vid-case -o node=@^1:^1:/2/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2/2 marked=on focus=off

## LAUNCH COMMANDS 
visualizer -w &
urxvtc -name "tty-clock" -title "tty-clock" --transparent --color1 red -e sh -c "tty-clock -r -t -C 1" &
mpv --x11-name="vid-case" --title="vid-case" $(while IFS= read -r line
do 
    echo "$line" | grep ^C: | tail -n $tag_count | tail -c +3 | tr '\n' ' '
done < ~/.config/ranger/tagged) &
c-gotop -kt &
sleep .5s; bspc desktop --focus ^2:focused

############
#   DARK   #
#############
elif [[ $1 = "-dark" ]]; then

## INSERT RECEPTACLES
bspc node @^1:^1:/ -i 
bspc node @^1:^1:/ -o .52 -p east -i
bspc node @^1:^1:/1 -o .498 -p south -i

## ADD RULES
bspc rule -a URxvt:cava -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2 marked=on focus=off
bspc rule -a URxvt:tty-clock -o node=@^1:^1:/1/2 marked=on focus=off

##LAUNCH APPS
urxvtc -name "cava" -title "cava" -bg white -bd black -e sh -c "cava -p ~/.config/cava/config_2" &
c-gotop -kt &
urxvtc -name "tty-clock" -title "tty-clock" -bg black -bd black --color1 white -e sh -c "tty-clock -c -t -C 1" &

##FOCUS PRIMARY MONITOR
sleep .5s; bspc desktop --focus ^2:focused

###############
#   MINIMAL   #
###############
else

##INSERT RECEPTACLES
bspc node @^1:^1:/ -i 
bspc node @^1:^1:/ -o 0.5 -p east -i
bspc node @^1:^1:/1 -o 0.133444 -p south -i

##ADD RULES
bspc rule -a URxvt:tty-clock -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2 marked=on focus=off
bspc rule -a URxvt:transparent -o node=@^1:^1:/1/2 marked=on focus=off

##LAUNCH APPS
urxvtc -name "tty-clock" -title "tty-clock" --transparent --color1 red -e sh -c "tty-clock -c -t -C 1" &
c-gotop -kt &
c-urxvtc-trans 
##FOCUS PRIMARY MONITOR
sleep .5s; bspc desktop --focus ^2:focused
fi
