#!/bin/sh

bspc desktop --focus ^2:^5

bspc node @^2:^5:/ -i
bspc node @^2:^5:/ -o 0.52 -p east -i

bspc rule -a Alacritty:ranger -o node=@^2:^5:/1 state=pseudo_tiled
bspc rule -a URxvt:TANK -o node=@^2:^5:/2 state=pseudo_tiled
 
alacritty --title "ranger" --class "ranger" -e sh -c \
"ranger --selectfile='Pictures/wal/v/LILIs_FILM_2.webm' \
--cmd='set preview_images_method ueberzug'" &
message 
