#!/bin/sh

############
#   RACH   #
############
if [[ $1 = "-r" ]]; then

##MOVE TO DESKTOP + CLOSE WINDOWS + KILL RECEPTACLES
bspc desktop -f ^2:^3;
while bspc node 'any.leaf.local' -c; do :; done;
while bspc node 'any.leaf.!window.local' -k; do :; done;

##INSERT RECEPTACLES
bspc node @^2:^3:/ -i
bspc node @^2:^3:/ -o 0.311854 -p east -i
bspc node @^2:^3:/2 -o 0.505506 -p east -i
bspc node @^2:^3:/2/2 -o 0.516098 -p south -i

##ADD RULES
bspc rule -a feh:feh -o node=@^2:^3:/1
bspc rule -a URxvt:TANK -o node=@^2:^3:/2/1
bspc rule -a URxvt:ranger -o node=@^2:^3:/2/2/1
bspc rule -a mpv:wide -o node=@^2:^3:/2/2/2

##LAUNCH APPS
feh -Z -. -D 5 ~/Pictures/chx/rachel/ &
message &
c-ranger &
mpv --x11-name="wide" --title="wide" ~/Videos/h/rachel/*.m4v

##########
#   EM   #
##########
elif [[ $1 = "-em" ]]; then

##MOVE TO DESKTOP + CLOSE WINDOWS + KILL RECEPTACLES
bspc desktop -f ^2:^6; 
while bspc node 'any.leaf.local' -c; do :; done;
while bspc node 'any.leaf.!window.local' -k; do :; done;

## INSERT RECEPTACLES
bspc node @^2:^6:/ -i
bspc node @^2:^6:/ -o 0.323488 -p east -i
bspc node @^2:^6:/2 -o 0.545 -p south -i
bspc node @^2:^6:/2/1 -o 0.5 -p east -i
bspc node @^2:^6:/2/2 -o 0.5 -p east -i

## ADD RULES
bspc rule -a feh:feh -o node=@^2:^6:/1
bspc rule -a Alacritty:ranger-em -o node=@^2:^6:/2/1/1 
bspc rule -a firefox:Navigator -o node=@^2:^6:/2/1/2
bspc rule -a mpv:em1 -o node=@^2:^6:/2/2/1
bspc rule -a mpv:em2 -o node=@^2:^6:/2/2/2

## LAUNCH APPS
feh -Z -. -D 5 ~/Pictures/chx/em/em-tall-* &
alacritty --title "ranger-em" --class "ranger-em" -e sh -c \
"~/.scripts/ranger/ranger.py \
--cmd='set preview_images_method ueberzug' \
--cmd='default_linemode devicons2' \
--cmd='set column_ratios 1,1,6' \
--selectfile='Pictures/chx/em/em-wide-murica.jpg'" &
firefox &
mpv --x11-name="em1" --title="em1" ~/Videos/h/wide/*em.mp4 &
mpv --x11-name="em2" --title="em2" ~/Videos/h/wide/*em2.mp4 

###########
#   CHX   #
###########
else
tag_count=$(grep -c ^v: ~/.config/ranger/tagged)

##MOVE TO DESKTOP + CLOSE WINDOWS + KILL RECEPTACLES
bspc desktop -f ^2:^5;
while bspc node 'any.leaf.local' -c; do :; done;
while bspc node 'any.leaf.!window.local' -k; do :; done;

## INSERT RECEPTACLES
bspc node @^2:^5:/ -i
bspc node @^2:^5:/ -o 0.210169 -p east -i
bspc node @^2:^5:/2 -o 0.265023 -p east -i

## ADD RULES
bspc rule -a mpv:alexa -o node=@^2:^5:/1
bspc rule -a mpv:h -o node=@^2:^5:/2/1
bspc rule -a Alacritty:ranger -o node=@^2:^5:/2/2

## LAUNCH APPS
mpv --x11-name="alexa" --title="alexa" ~/Videos/h/ap/ --video-zoom=0.2 &
mpv --x11-name="h" --title="h" $(while IFS= read -r line
do 
    echo "$line" | grep ^v: | tail -n $tag_count | tail -c +3 | tr '\n' ' '
done < ~/.config/ranger/tagged) --video-zoom=0.2 &
alacritty --class "ranger" --title "ranger" -e sh -c \
"~/.scripts/ranger/ranger.py \
--cmd='set preview_images_method ueberzug' \
~ \
--selectfile=$(grep ^H: ~/.config/ranger/tagged | tail -1 | tail -c +3)"
fi
