#! /bin/sh
xfsettingsd &
xcape -e 'Super_L=Super_L|D' &
setxkbmap -option caps:swapescape &
sxhkd &
picom &
urxvtd -q &
mpd &
skippy-xd --config ~/.config/skippy-xd/skippy-xd.rc --start-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xdg-user-dirs-gtk-update &

bspc config focus_follows_pointer true

bspc monitor -d 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config normal_border_color "#887E80"
bspc config active_border_color "#5E81AC"
bspc config focused_border_color "#00E7FF"
