#! /bin/sh

## Compositor
sleep .5s; picom -b &

## swap caps and escape buttons
sleep .5s; setxkbmap -option caps:swapescape &

## Keybinds
sleep .5s; sxhkd &

## super key for menu
xcape -e 'Super_L=Super_L|D' &

## font
xset +fp ~/.fonts/misc/ &

### PolicyKit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

### Localize user system folders
xdg-user-dirs-gtk-update &

## skippy windowswitcher
skippy-xd --config ~/.config/skippy-xd/skippy-xd.rc --start-daemon &

## Apps
easystroke &
urxvtd -q &
mpd &

## xfce4-settings daemon
sleep .5s; xfsettingsd &
#sleep .5s; nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceCompositionPipeline=On, ForceFullCompositionPipeline=On }" &

bspc config focus_follows_pointer true

#mouse refresh rate (1000/100hz=10)
bspc config pointer_motion_interval 10

bspc monitor HDMI-1-2 -d C 
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a MEGAsync state=floating desktop='^4'
bspc rule -a Gcolor3 state=floating
bspc rule -a Surf state=tiled

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color12"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color2"
