#!/usr/bin/env sh
# >>> conda initialize >>>
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
conda activate flix
# <<< conda initialize <<<
 . .scripts/colors/getcolors

echo -e "\n"
figlet -f ANSI_Shadow " Netflix?" | gterm $RED
figlet -f ANSI_Shadow "...................." | gterm $WHITE
figlet -f future.tlf "     More Like"
echo -e "\n"
figlet -f ANSI_Shadow "    Not" | gterm $MAGENTA $CYAN #$GREEN $YELLOW
figlet -f ANSI_Shadow "       -" #| gterm $RED #$GREEN
figlet -f ANSI_Shadow "    FLIX" | gterm $MAGENTA $CYAN #$RED $GREEN $YELLOW
echo -e "\n\n\n"
echo -e "\t\t\t(Got 'em)"
echo -e "\n"
python ${HOME}/dev/flix-cli/flix-cli.py
