#!/usr/bin/env sh


while getopts g:h:t:b: option
do
    case "${option}"
    in
        h)horizontal=${OPTARG};;
        g)gaps=${OPTARG};;
        t)top=${OPTARG};;
        b)bottom=${OPTARG}
    esac
done

bspc config -m focused left_padding "$horizontal" &
bspc config -m focused right_padding "$horizontal" &
bspc config -m focused top_padding "$vertical" &
bspc config -m focused bottom_padding "$vertical" &
bspc config -m focused window_gap "$gaps"

