#!/bin/sh
case $1 in

    '--compix')
        pkill picom ;
        sleep .3s ;
        cd ~/.config/picom/compix/out ; 
        ./compix -c ../compix.conf &
    ;;
    
    '--picom')
        pkill compix;
        sleep .3s;
        picom -b \
            #--experimental-backends;
    ;;
esac
