#!/usr/bin/env sh
case $1 in

    '--compix')
        pkill picom 
        sleep .5s 
        cd ${HOME}/.config/picom/compix/out  
        ./compix -c ../compix.conf & 
    ;;
    
    '--picom')
        pkill compix && picom -b  
    ;;
esac
