#!/bin/sh
case $1 in
    "-bar")
        ~/.config/eww/bar/launch_bar
        bspc config -m HDMI-0 window_gap 51
    ;;

    "-bar2")
       /home/ellio/.config/eww/bar_2/launch_eww    
       bspc config -m focused left_padding 75
    ;; 
    
    "-left")
        /home/ellio/.config/eww/leftbar/launch_left
    ;;

   "-dashboard")
        /home/ellio/.config/eww/dashboard/dashboard
    ;;

    "-dashboard2")
        /home/ellio/.config/eww/dashboard_2/launch_eww
    ;;

    "-kill")
        bspc config -m focused top_padding 0
        bspc config -m focused left_padding 0
        bspc config -m HDMI-0 window_gap 0
        pkill eww
    ;;
esac
