#!/usr/bin/env sh
logOutput(){

cat<<EOF
===
launcher: $dir
style: $theme
config: ${dir}/${theme}.rasi"
EOF
}

case $1 in
    '-r')
        dir=$(find /home/ellio/.config/rofi/launchers -iname "type*" | shuf | tail -n 1)
        theme=$(find $dir -iname "style-*" | grep -oE "style.*[0-9]" | shuf | tail -n1)
        logOutput >> ~/.scripts/tmp/rofi
        rofi \
            -show drun \
            -theme ${dir}/${theme}.rasi
        ;;

    '')
        rofi -show run
        ;;
esac    
