#!/usr/bin/env sh

dir=$(find /home/ellio/.config/rofi/launchers -iname "type*" | shuf | tail -n 1)
theme=$(find $dir -iname "style-*" | grep -oE "style.*[0-9]" | shuf | tail -n1)

echo -n "

===
launcher: $dir
style: $theme
config: ${dir}/${theme}.rasi" >> ~/.scripts/tmp/rofi

rofi \
    -show drun \
    -theme ${dir}/${theme}.rasi
