#!/bin/sh
url(){
    sleep .3s;
    xdotool click 2; 
    sleep 1s; 
    xdotool key ctrl+l; 
    sleep 1s; 
    xdotool key ctrl+c
}

tags="/home/ellio/.config/ranger/tagged"
    
case $1 in
    "")
        dir="/home/ellio/Videos/h"
        tag="v"
    ;;
        
    "-x")
        dir="/home/ellio/Videos/h/wide"
        tag="x"
    ;;
    
    "-p")
        dir="/home/ellio/Pictures/chx"
        tag="p"
    ;;
esac
    
cd $dir;
wget "$(xclip -out secondary)";
file="$(ls -c | head -n 1)"
echo "$tag:$dir$file" >> $tags
