#!/bin/sh

if [[ $1 = "-d" ]]; then
url=$(dragon-drag-and-drop -t -x)

if [ -n "$url" ]; then
printf "File Name: "
name=""
while [ -z $name ] || [ -e $name ]
do
    read -r name
    if [ -e "$name" ]; then
        printf "File already exists, overwrite (y|n): "
        read -r ans
        
        if [ "$ans" = "y" ]; then
        break
        else
        printf "File Name: "
        fi
    fi
done
# Download the file with curl
[ -n "$name" ] && curl -o "$name" "$url" || exit 1
else
  exit 1
fi

else
files=$(dragon-drag-and-drop -t -x)

for file in $files
do
    path=${file#file://}
    name=$(basename "$path")
    cp "$path" "$(pwd)/$name"
done
fi
