#!/usr/bin/env sh
dir="/run/media/ellio/T7/bdfr"
cd $dir

CloseTerm(){
    xdotool windowclose $window 
}

QueryAllFiles(){
    echo "path,id,score,time" > $dir/RH.csv
    fd --full-path "$dir" --extension=mp4 --extension=json $dir/fav -x \
    jq --arg e {//} -r '. |= . + {"$e": "$e"} | [$e, .id, .score, .created_utc] | @csv' {.}.json 2>/dev/null | tee --append $dir/RH.csv
}

QuerySub(){
        sub=$1
        sort=$2
        csvgrep -c 1 -r ".$sub" $dir/RH.csv | csvsort -c "$sort" -r | csvcut -c 1-2 | sed 's/,/\//g' | sed 's/$/.mp4/g' | uniq
}

download(){
    #echo "Subreddit: "
    #read subreddit
    #echo "Sort: "
    #read srt
    #echo "Time: "
    #read time
    time='all'
    srt='top'
    subreddit=$1
    python3 -m bdfr clone $dir \
    -s "$subreddit" \
    -t $time \
    -S $srt \
    --file-scheme '{POSTID}' \
    --search-existing \
    --no-dupes
}

search(){
        folder="$(echo "$query" | sed 's/ //g')"

        python3 -m bdfr clone $dir/search/$folder \
        --subreddit "all" \
        --sort "top" \
        --time "all" \
        --user "DontWorryAboutIt88"\
        --authenticate \
        --file-scheme '{POSTID}' \
        --search "'$query'" 
}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup

conda activate bdfr
# <<< conda initialize <<<

case $1 in
    "-r"| "--refresh")
        QueryAllFiles 
    ;;

    "-d" | "--download")
        download $2
    ;;
    
    "-s" | "--search")
        query="$2"
        search
    ;;

    "-S")
        nohup mpv $(QuerySub "$2" "$3")
    ;;
esac
