#!/usr/bin/env sh
dir="/mnt/PSSD_Storage/bdfr/fav"

CloseTerm(){
    xdotool windowclose $window 
}

PlayVids(){
   nohup mpv --playlist-start=0 $(while IFS= read -r line; do echo $line; done < /tmp/subs) 
}

view(){
    PS3="Enter Subreddit: "
    window=$(xdotool getactivewindow)

    select subreddit in $(ls $dir)                
    do                                                                                              
        ls -tr $dir/$subreddit/*.mp4 | tail -n 100 > /tmp/subs                                            
        PlayVids & CloseTerm     
    done
}

download(){
    echo "Subreddit: "
    read subreddit
    echo "Sort: "
    read srt
    echo "Time: "
    read time

    python3 -m bdfr download $dir -s "$subreddit" \
    -t $time \
    -S $srt \
    --file-scheme '{POSTID}' \
    --search-existing \
    --no-dupes
}

rndm(){
    window=$(xdotool getactivewindow)
    
    urxvtc -e sh -c "ranger $dir ${HOME}/Videos/h/"
    for f in $(ls $dir)
    do
            ls -tr $dir/$f/*.mp4 | tail -n 50
    done | shuf > /tmp/subz
    
    nohup mpv --playlist-start=0 $(while IFS= read -r line; do echo $line; done < /tmp/subz) &
    CloseTerm
}

update(){
    #Ghetto Multiprocessing 
    echo "Process Number: "
    read p
    #List of All Subreddits to update
    subreddits=$(ls $dir)
    #Subreddit Math to Split into Two Groups
    total_subreddit_count=$(echo "$subreddits" | wc -l)
    one_third_of_subreddit_count=$(bc <<<$total_subreddit_count/3)
    #Split the List of All Subreddits Into Thirds
    subreddit_array=($(xargs -n $one_third_of_subreddit_count <<<$subreddits | tr ' ' ','))
    subs=$(echo ${subreddit_array[$p]})
     
    #Run BDFR
    echo 
    echo "-->>> $subs -->>>"
    echo    
    python3 -m bdfr download $dir \
        -s "$subs" \
        -t month \
        -S top \
        --file-scheme '{POSTID}'\
        --search-existing \
        --no-dupes
    echo 
    echo "<<<-- $subs <<<--"
    echo
}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate bdfr
case $1 in
    ""| " ")
        view
    ;;

    "-s" | "--search")
        download
    ;;

    "-r" | "--random")
        rndm
    ;;

    "-u" | "--update")
        update 
    ;;
esac 
