#!/bin/bash

tfn="$(date +%F_%T)"

remux-concat(){                                    
        files=($@)
        tmpDir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
        timeStamp=$(date "+%Y%m%d-%H%M%S%3N")
        
        touch $tmpDir/vidlist.txt

        for f in $files
        do
                echo "file '$f'" >> $tmpDir/vidlist.txt
        done

        ffmpeg -f concat -safe 0 -i $tmpDir/vidlist.txt -c copy $(output_$timeStamp).mp4
}

case $1 in

    "-t" | "--trim")
        
        ffmpeg -i $input -ss $startTime -to $endTime -c copy output_$tfn
        ;;

    "-sbs" | "--side-by-side")  
        
        ffmpeg -i $1 -i $2 -filter_complex hstack -c:v libx264 -crf 20 $file_timestamp.mp4
        ;;

    "-c" | "--concat")
        
        remux-concat
        ;;

    '')

        cat ${HOME}/.scripts/system_exec/remux | grep -o -e '"-.*"' | sd '"' '' 
        ;;

esac

