#!/bin/bash
if [[ $1 = "-trim" ]]; then
#inpoint=$(xclip -out -selection clipboard)
echo input file:
read input
echo output file:
read output
echo start time: 
read st
echo end time:
read et
ffmpeg -i $input -ss $st -to $et -c copy $output

elif [[ $1 = "-format" ]]; then
echo input file:
read input
echo output file:
read output
ffmpeg -i $input -codec copy $output

elif [[ $1 = "-concat" ]]; then
echo output file:
read output  
ffmpeg -f concat -safe 0 -i ~/vidlist.txt -c copy $output
fi
