#!/bin/sh
source ${HOME}/.scripts/colors/getcolors
font="${HOME}/.fonts/misc/figlet/ANSI_Shadow.flf"
figlet -f $font 'Back-Up' | gterm "$RED" "$GREEN" ;

tsd=$(sudo timeshift --list | grep -oe ">.*  " | sed 's/>  \|  .*//g' | head -n 2 | tail -n 1)

if [[ $1 = "-d" ]]; then
sudo timeshift --list; \
sudo timeshift --delete --snapshot $tsd; \
zsh

elif [[ $1 = "-c" ]]; then
read -p 'comment: ' comment
sudo timeshift --list; \
sudo timeshift --delete --snapshot $tsd; \
sudo timeshift --create --comments "$comment"; \
zsh

else
sudo timeshift --list; \
sudo timeshift --delete --snapshot $tsd; \
sudo timeshift --create --comments "house-keeping"; \
zsh
fi

notify-send --urgency=normal \
--expire-time=45000 \
--app-name="custom app" \
--icon=${HOME}/Pictures/sbpt.png \
--category="my category" \
"Backup Complete"
