#!/bin/sh
tag_count=$(grep -c ^V: ~/.config/ranger/tagged)
case $1 in
    '')
        zoom="0"
        pos="0"
        ;;
    "-w")
        zoom="2.1"
        pos="-0.22"
        ;;
esac

mpv --x11-name="bm" \
    --video-zoom="$zoom" \
    --video-pan-y="$pos" \
    mpv $(cat  ~/.config/ranger/tagged | grep -oe "^V.*$" | sd 'V:' '')
