#!/bin/sh
tag_count=$(grep -c ^V: ~/.config/ranger/tagged)
bspc rule -a mpv:bm -o state=pseudo_tiled

mpv --x11-name="bm" $(while IFS= read -r line
do 
    echo "$line" | grep ^V: | tail -n $tag_count | tail -c +3 | tr '\n' ' '
done < ~/.config/ranger/tagged)
