#!/bin/sh
##VARIABLES##
dt=$(bspc query --desktops --names --desktop .\!occupied | head -n 1)
tag_count=$(grep -c ^W: ~/.config/ranger/tagged)

##DESKTOP FOCUS
bspc desktop -f ^2:^$dt;

if [[ $1 = "-s" ]]; then

    ##NODE RULES
    bspc rule -a wp-vid1:wp-vid1 -o state=pseudo_tiled
    bspc rule -a ranger:ranger -o state=pseudo_tiled

    ##MAIN VID
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid1" --class "wp-vid1" -e sh -c "
    xwinwrap -g 3440x1440+1280+0 -ov -- mpv -wid WID $(while IFS= read -r line
    do 
        echo "$line" | grep ^W: | tail -n $tag_count | tail -c +3 | tr '\n' ' ':
    done < ~/.config/ranger/tagged) --video-zoom=0.4" & 

    ##RANGER
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "ranger" --class "ranger" -e sh -c \
    "ranger --selectfile=$(grep ^W: ~/.config/ranger/tagged | tail -1 | tail -c +3) \
    --cmd='set preview_images_method ueberzug'"
    
elif [[ $1 = "-p" ]]; then
    
    ##NODE RULES
    bspc rule -a kitty:wp-vid2 -o state=pseudo_tiled  

    ##MAIN VID
    vids="/home/ellio/Videos/h_US/compressed_DASH_720.15_scale_1x_alq-13_scale_3x_prob-3_s4_f30_chr-2.mp4 \
    /home/ellio/Videos/h_US/compressed_tg0fgp_scale_1x_alq-13_scale_2x_prob-3_s4_f30_chr-2.mp4 \
    /home/ellio/Videos/h_US/compressed_tggery_scale_1x_alq-13_scale_2x_prob-3_s4_f30_chr-2.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/compressed_dash_1080_03_scale_1x_alq-13_scale_2x_prob-3_s4_f30_chr-2.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/compressed_emma-wilcott-03_scale_1x_alq-13_scale_2x_prob-3_s4_f30.03_chr-2.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/3_scale_1x_alq-13_scale_3x_prob-3_s4_f30_chr-2.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/OrangeColorfulCaimanlizard_scale_1x_alq-13_scale_2x_prob-3_s4_f30.01_chr-2.mp4"

    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid2" --name "wp-vid2" -e sh -c "
    xwinwrap -g 3440x1440+1280+0 -ov -- mpv -wid WID $vids --video-zoom=2.1 --video-pan-y=-0.25"

else    
    ##INSERT NODES
    bspc node @^2:^$dt:/ -i 
    bspc node @^2:^$dt:/ -o .4 -p east -i
    bspc node @^2:^$dt:/2 -o .4 -p east -i
    bspc node @^2:^$dt:/1 -o .5 -p south -i
    bspc node @^2:^$dt:/2/1 -o .5 -p south -i
    
    ##NODE RULES
    bspc rule -a kitty:Display1 -o node=@^2:^$dt:/1/1 state=pseudo_tiled 
    bspc rule -a kitty:Display2 -o node=@^2:^$dt:/1/2 state=pseudo_tiled
    bspc rule -a kitty:wp-vid1 -o node=@^2:^$dt:/2/1/1 state=pseudo_tiled
    bspc rule -a kitty:wp-vid2 -o node=@^2:^$dt:/2/1/2 state=pseudo_tiled
    bspc rule -a ranger:ranger -o node=@^2:^$dt:/2/2 state=pseudo_tiled
    
    #MESSAGE
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "Display2" --name "Display2" -e sh -c \
    "figlet -f ~/.fonts/misc/figlet/ANSI_Shadow.flf '2';zsh" &
    
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "Display1" --name "Display1" -e sh -c \
    "figlet -f ~/.fonts/misc/figlet/ANSI_Shadow.flf '1';zsh" &
    
    ##MAIN VID
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid2" --name "wp-vid2" -e sh -c "
    xwinwrap -g 3440x1440+1280+0 -ov -- mpv -wid WID $(while IFS= read -r line
    do 
        echo "$line" | grep ^W: | tail -n $tag_count | tail -c +3 | tr '\n' ' ':
    done < ~/.config/ranger/tagged) --video-zoom=0.4" &
    
    sleep .5s;
    
    ##CASE VID
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid1" --name "wp-vid1" -e sh -c "
    xwinwrap -g 1276x1020+0+0 -ov -- mpv -wid WID $(while IFS= read -r line
    do 
        echo "$line" | grep ^W: | tail -n $tag_count | tail -c +3 | tr '\n' ' '
    done < ~/.config/ranger/tagged)" & 
    
    ##RANGER
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "ranger" --class "ranger" -e sh -c \
    "ranger --selectfile=$(grep ^W: ~/.config/ranger/tagged | tail -1 | tail -c +3) \
    --cmd='set preview_images_method ueberzug'" &
    
    layout-case -trans
fi
