#!/bin/sh
##VARIABLES##
dt=$(bspc query --desktops --names --desktop .\!occupied | head -n 1)
tag_count=$(grep -c ^W: ~/.config/ranger/tagged)

##DESKTOP FOCUS
bspc desktop -f ^2:^$dt;

if [[ $1 = "-s" ]]; then

    ##NODE RULES
    bspc rule -a wp-vid1:wp-vid1 -o state=pseudo_tiled
    bspc rule -a ranger:ranger -o state=pseudo_tiled

    ##MAIN VID
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid1" --class "wp-vid1" -e sh -c "
    mpv --video-zoom=0.4 --no-osc --no-ontop $(cat ~/.config/ranger/tagged | grep -o -e "W:.*$" | sd 'W:' '')" & 
    ##RANGER
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "ranger" --class "ranger" -e sh -c \
    "ranger --selectfile=$(grep ^W: ~/.config/ranger/tagged | tail -1 | tail -c +3) \
    --cmd='set preview_images_method ueberzug'"
    
elif [[ $1 = "-p" ]]; then
    
    ##NODE RULES
    bspc rule -a kitty:wp-vid2 -o state=pseudo_tiled  

    ##MAIN VID
    vids="/home/ellio/Videos/h_US/compressed_DASH_720.15_scale_1x_alq-13_scale_3x_prob-3_s4_f30_chr-2.mp4 \
    /home/ellio/Videos/h_US/compressed_tggery_scale_1x_alq-13_scale_2x_prob-3_s4_f30_chr-2.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/vx3.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/OrangeColorfulCaimanlizard_scale_1x_alq-13_scale_2x_prob-3_s4_f30.01_chr-2.mp4 \
    /home/ellio/Videos/h_US/p.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/sOhzg3o_scale_1x_alq-13_scale_2x_prob-3_s4_f30_chr-2.mp4 \
    /mnt/PSSD_Storage/UpScale/h/bulk/jP8A0Lk_scale_1x_alq-13_scale_2x_prob-3_s4_f59.94_chr-2.mp4 \
    /home/ellio/Videos/h_US/compressed_nzAk7A4_scale_1x_alq-13_scale_2x_prob-3.mp4 \
    /home/ellio/Videos/h_US/compressed_u3pt2b_scale_1x_alq-13_scale_2x_prob-3_s4_f30_chr-2.mp4"

    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid2" --name "wp-vid2" -e sh -c "
    mpv --no-osc --no-ontop --video-zoom=2.1 --video-pan-y=-0.25 $vids "

else    
    ##INSERT NODES
    bspc node @^2:^$dt:/ -i 
    bspc node @^2:^$dt:/ -o .4 -p east -i
    bspc node @^2:^$dt:/2 -o .4 -p east -i
    bspc node @^2:^$dt:/1 -o .5 -p south -i
    bspc node @^2:^$dt:/2/1 -o .5 -p south -i
    
    ##NODE RULES
    bspc rule -a kitty:Display1 -o node=@^2:^$dt:/1/1 state=pseudo_tiled 
    bspc rule -a kitty:Display2 -o node=@^2:^$dt:/1/2 state=pseudo_tiled
    bspc rule -a kitty:wp-vid1 -o node=@^2:^$dt:/2/1/1 state=pseudo_tiled
    bspc rule -a kitty:wp-vid2 -o node=@^2:^$dt:/2/1/2 state=pseudo_tiled
    bspc rule -a ranger:ranger -o node=@^2:^$dt:/2/2 state=pseudo_tiled
    
    #MESSAGE
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "Display2" --name "Display2" -e sh -c \
    "figlet -f ~/.fonts/misc/figlet/ANSI_Shadow.flf '2';zsh" &
    
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "Display1" --name "Display1" -e sh -c \
    "figlet -f ~/.fonts/misc/figlet/ANSI_Shadow.flf '1';zsh" &
    
    ##MAIN VID
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid2" --name "wp-vid2" -e sh -c "
    mpv --no-osc --no-ontop --video-zoom=0.4 $(cat ~/.config/ranger/tagged | grep -o -e "W:.*$" | sd 'W:' '')" &    
    sleep .5s;
    
    ##CASE VID
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "wp-vid1" --name "wp-vid1" -e sh -c "
    mpv --no-osc --no-ontop --video-zoom=0.4 $(cat ~/.config/ranger/tagged | grep -o -e "W:.*$" | sd 'W:' '')" &

    ##RANGER
    kitty -o include=~/.config/kitty/kitty-transparent.conf --title "ranger" --class "ranger" -e sh -c \
    "ranger --selectfile=$(grep ^W: ~/.config/ranger/tagged | tail -1 | tail -c +3) \
    --cmd='set preview_images_method ueberzug'" &
    
    layout-case -trans
fi
