#!/usr/bin/env sh
encrypt(){
    openssl enc -aes-256-cbc -a -A -md sha512 -pbkdf2 -iter 250000 -salt $@
}

decrypt(){
    openssl enc -aes-256-cbc -a -A -d -md sha512 -pbkdf2 -iter 250000 -salt $@
}

case $1 in
    "-e" | "-encrypt")

        while getopts ef:s:ca: option
        do 
           case "${option}"
                in
                f)file=${OPTARG}; encrypt -in $file -out $(echo $file|cut -d '.' -f1).dat;;
                s)string=${OPTARG}; echo $string | encrypt | xclip;;
                c)clip=${OPTARG}; xclip -out -selection primary | encrypt | xclip;;
                k)pubkey=${OPTARG}; openssl rsautl -encrypt -inkey $pubkey -pubin -in $file -out top_secret.dat
            esac
        done
        ;;

    "-d" | "-decrypt")
        while getopts df:s:ca: option
        do 
           case "${option}"
                in
                f)decrypt -in ${OPTARG} -out unencrypted$(date +%Y%m%dT%H%M%S);;
                s)echo ${OPTARG} | decrypt;;
                c)echo "$(xclip -out -selection primary)" | decrypt;;
                k)privatekey=${OPTARG}; openssl rsautl -decrypt -inkey $privatekey -in $@
            esac
        done
        ;;

    "--generate-private-key")
        openssl genrsa -aes256 -out private_key.pem 8912 #1024 #8912
        ;;

    "--extract-public-key")
        openssl rsa -in private_key.pem -out public_key.pem -outform PEM -pubout
        ;; 
esac
