#!/usr/bin/env sh
encrypt(){
    openssl enc -aes-256-cbc -a -A -md sha512 -pbkdf2 -iter 250000 -salt $@
}

decrypt(){
    openssl enc -aes-256-cbc -a -A -d -md sha512 -pbkdf2 -iter 250000 -salt $@
}

case $1 in
    "-e" | "-encrypt")

        while getopts ef:s: option
        do 
           case "${option}"
                in
                f)encrypt -in ${OPTARG} -out $(tfn).dat;;
                s)echo ${OPTARG} | encrypt | xclip;;
            esac
        done
        ;;

    "-d" | "-decrypt")
        while getopts df:s:c option
        do 
           case "${option}"
                in
                f)decrypt -in ${OPTARG} -out encrypted_$(tfn);;
                s)echo ${OPTARG} | decrypt;;
                c)echo "$(xclip -out -selection primary)" | decrypt;;
            esac
        done
        ;;

    "--generate-private-key")
        openssl genrsa -aes128 -out private_key.pem 1024 #8912
        ;;

    "--extract-public-key")
        openssl rsa -in private_key.pem -out public_key.pem -outform PEM -pubout
        ;;
    
esac

#encrypt 
#openssl rsautl -encrypt -inkey bob_public.pem -pubin -in top_secret.txt -out top_secret.enc
#decrypt
#openssl rsautl -decrypt -inkey bob_private.pem -in top_secret.enc 
