#!/bin/sh
mods=($(genact -l | sed 's/^.*://g' | sd '\n' ''))
font="${HOME}/.fonts/misc/figlet/ANSI_Shadow.flf"
time_limit=$(shuf -i 10-60 -n1)
source ${HOME}/.scripts/colors/getcolors

colorize(){
    case $1 in
        1)
            gterm "$RED" "$GREEN"
            ;;
        2)
            gterm "$YELLOW" "$BLUE"
            ;;
        3)
            gterm "$BLUE" "$MAGENTA" "$CYAN" "$WHITE"
            ;;
    esac
}

while true;
do
    for m in ${mods[@]}
    do
        i=$(shuf -i 1-3 -n1)
        echo
        figlet -f $font $m | colorize $i
        echo
        genact -m $m \
            --exit-after-time "$time_limit"s \
            -s 1 
    done
done
