#!/bin/sh
##Variables##
random_scheme=$(ls -d ~/.config/kitty/cs/* | shuf -n 1)
dt=$(bspc query --desktops --names --desktop .\!occupied | head -n 1)

##REMOVE PREVIOUS CS##
sed -i '/include/d' ~/.config/kitty/kitty-fulltop.conf

##ADD NEW CS##
echo "include $random_scheme" >> ~/.config/kitty/kitty-fulltop.conf

##SWTICH DESKTOP
bspc desktop -f ^2:^$dt;

##INSERT RECEPTACLES
bspc node @^2:^$dt:/ -i
bspc node @^2:^$dt:/ -o .5 -p east -i

##ADD RULES
bspc rule -a kitty:Fullgotop -o node=@^2:^$dt:/1
bspc rule -a kitty:Fullnvtop -o node=@^2:^$dt:/2

##LAUNCH APPS
kitty --name "Fullgotop" --title "Fullgotop" -o include="/home/ellio/.config/kitty/kitty-fulltop.conf" -e sh -c \
"gotop --nvidia --averagecpu --statusbar --mbps --layout kitchensink" & \
sleep .5s; \
kitty --name "Fullnvtop" --title "Fullnvtop" -o include="/home/ellio/.config/kitty/kitty-fulltop.conf" -e sh -c "nvtop" & \
notify-send -u normal "$(echo $random_scheme)"
