#!/bin/sh
##Variables##
random_scheme=$(ls -d ~/.config/kitty/cs/* | shuf -n 1)
scheme_name=$(echo $random_scheme | grep -o "cs/.*" | cut -d "/" -f2 | rev | cut -c 6- | rev)
dt=$(bspc query --desktops --names --desktop .\!occupied | head -n 1)

##REMOVE PREVIOUS CS##
#sed -i '/include/d' ~/.config/kitty/kitty-fulltop.conf

##ADD NEW CS##
#echo "include $random_scheme" >> ~/.config/kitty/kitty-fulltop.conf

##SWTICH DESKTOP
bspc desktop -f ^2:^$dt;

##INSERT RECEPTACLES
bspc node @^2:^$dt:/ -i
bspc node @^2:^$dt:/ -o .5 -p east -i
bspc node @^2:^$dt:/2 -o .5 -p south -i
##ADD RULES
bspc rule -a kitty:Fullgotop -o node=@^2:^$dt:/1
bspc rule -a kitty:Fullnvtop -o node=@^2:^$dt:/2/1
bspc rule -a kitty:Fullhtop -o node=@^2:^$dt:/2/2

##LAUNCH APPS
kitty --name "Fullgotop" --title "Fullgotop" \
-o include="/home/ellio/.config/kitty/kitty-fulltop.conf" \
-e sh -c \
"gotop --nvidia --statusbar --mbps --layout kitchensink" & \
sleep .5s; \

kitty --name "Fullnvtop" --title "Fullnvtop" \
-o include="/home/ellio/.config/kitty/kitty-fulltop.conf" \
-e sh -c "nvtop" &

kitty --name "Fullhtop" --title "Fullhtop" \
-o include="/home/ellio/.config/kitty/kitty-fulltop.conf" \
-e sh -c "htop"
