#!/bin/sh

if [[ $1 = "-clock" ]]; then
kitty --name "tty-clock" --title "tty-clock" -o include="~/.config/kitty/kitty-transparent.conf" \
-e sh -c \
"tty-clock -c -t -C 1;zsh"

else
kitty --name "transparent" --title "transparent" -o include="~/.config/kitty/kitty-transparent.conf"
fi
