#!/bin/sh
if [[ $1 = "-ascii" ]]; then
kitty --name "neofetch-ascii" --title "neofetch-ascii" -e sh -c \
'neofetch --ascii "$(figlet -f ~/.fonts/misc/figlet/isometric.flf T)"; \
zsh'

elif [[ $1 = "-pic" ]]; then
kitty --name "neofetch-pic" --title "neofetch-pic" -e sh -c \
"neofetch --crop_mode fill --bg_color white --kitty \
$(grep ^n:  ~/.config/ranger/tagged | tail -n 1 | tail -c +3) \
--kitty; zsh"

elif [[ $1 = "-wal" ]]; then
kitty --name "neofetch" --title "neofetch" -e sh -c \
"neofetch --bg_color white --kitty; zsh"

elif [[ $1 = "-f" ]]; then
kitty --name "neofetch" --title "neofetch" -e sh -c \
"neofetch --bg_color white --kitty $(grep ^N:  ~/.config/ranger/tagged | tail -n 1 | tail -c +3); zsh"
fi
