#!/bin/sh
source /usr/share/autojump/autojump.bash

##################
#   MINIMAL-UI   #
##################
if [[ $1 = "-s" ]]; then
urxvtc -name "ranger" -title "ranger" -e sh -c \
"~/.scripts/ranger/ranger.py"

########################
#   MINIMAL-UI KITTY   #
########################
elif [[ $1 = "-ks" ]]; then
kitty --name "ranger" --title "ranger" -e sh -c \
"~/.scripts/ranger/ranger.py \
--cmd='set preview_images_method ueberzug' \
--cmd='default_linemode devicons2' \
--cmd='set draw_borders false' \
~ \
--selectfile=$(grep ^h: ~/.config/ranger/tagged | tail -1 | tail -c +3)"

#################
#   ALACRITTY   #
#################
elif [[ $1 = "-a" ]]; then
alacritty --title "ranger" --class "ranger" -e sh -c \
"ranger \
--cmd='set preview_images_method ueberzug' \
--cmd='set draw_borders false' \
--selectfile=$(grep ^h: ~/.config/ranger/tagged | tail -1 | tail -c +3)"

#############
#   KITTY   #
#############
elif [[ $1 = "-k" ]]; then
kitty --name "ranger" --title "ranger" -e sh -c \
"ranger \
--cmd='set preview_images_method ueberzug' \
--cmd='default_linemode devicons2' \
--cmd='set draw_borders false'"

##############
#   URXVTC   #
##############
else
urxvtc -name "ranger" -title "ranger" -e sh -c \
"ranger \
--selectfile=$(grep ^h: ~/.config/ranger/tagged | tail -1 | tail -c +3)"
fi
