#!/bin/sh

if [[ $1 = "-ct" ]]; then
    kitty --name "cointop" --title "cointop" -e sh -c "docker run -it cointop/cointop"
elif [[ $1 = "--ticker" ]]; then
    kitty --name "ticker" --title "ticker" -e "ticker"
else
    kitty --name "xmr" --title "xmr" -e sh -c \
    "superstonk \
    -interval 10 \
    -shares 33.065605913502 \
    -symbol xmr-usd"
fi
