#!/bin/sh

#rectangles,pagga,spliff,Ansi_Regular,Ansi_Shadow,future

rndm_font=$(echo $(ls -d ~/.fonts/misc/figlet/* | shuf -n 1) | grep -o "figlet/.*" | cut -d "/" -f2 | rev | cut -c 5- | rev)

#################
#   ALACRITTY   #
#################
if [[ $1 = "-a" ]]; then
alacritty --class "TANK-A" --title "TANK-A" -e sh -c \
'figlet -f ~/.fonts/misc/figlet/Rectangles.flf 'TANK'; \
zsh'

#############
#   kitty    #
#############
elif [[ $1 = "-k" ]]; then
kitty --name "TANK-K" --title "TANK-K" -e sh -c \
'figlet -f ~/.fonts/misc/figlet/Rectangles.flf 'TANK'; \
zsh'

elif [[ $1 = "-kt" ]]; then
c-kitty-trans

#############
#   ADMIN   #
#####################
elif [[ $1 = "-A" ]]; then
alacritty --class "admin" --title "admin" -e sh -c \
"figlet -f ~/.fonts/misc/figlet/Rectangles.flf 'TANK'; \
sudo su;\
zsh"

##############
#   URXVTC   #
##############
else
urxvtc -title "TANK" -name "TANK" -e sh -c \
'figlet -f ~/.fonts/misc/figlet/Rectangles.flf 'TANK'; \
zsh'

fi
