#!/bin/sh

#################
#   ALACRITTY   #
#################
if [[ $1 = "-a" ]]; then
alacritty --class "TANK-A" --title "TANK-A" -e sh -c \
'figlet -f ~/.fonts/misc/figlet/rectangles.flf 'TANK'; \
zsh'

#############
#   kitty    #
#############
elif [[ $1 = "-k" ]]; then
kitty --name "TANK-K" --title "TANK-K" -e sh -c \
'figlet -f ~/.fonts/misc/figlet/rectangles.flf 'TANK'; \
zsh'

#############
#   ADMIN   #
#####################
elif [[ $1 = "-A" ]]; then
alacritty --class "admin" --title "admin" -e sh -c \
"figlet -f ~/.fonts/misc/figlet/rectangles.flf 'TANK'; \
sudo su;\
zsh"

##############
#   URXVTC   #
##############
else
urxvtc -title "TANK" -name "TANK" -e sh -c \
'figlet -f ~/.fonts/misc/figlet/rectangles.flf 'TANK'; \
zsh'

fi
