#!/bin/bash

file=$1

cat "$file" | curl -F 'f:1=<-' ix.io | xclip -selection c
notify-send "😀 pastebin for $file created."

url=$(echo "$(xclip -sel c -o)")
time=$(date '+%d-%m-%y-%H_%M_%S')
title="[$time] 	$url 	$file"
echo "$title" >> "$HOME/.scripts/paste_hist.txt"

firefox $url &

