#!/bin/bash

files=($@)
browser="librewolf"
links=()

for f in "${files[@]}"; 
do

    cat "$f" | curl -F 'f:1=<-' ix.io | xclip -selection c
    notify-send "😀 pastebin for $f created."

    url=$(echo "$(xclip -sel c -o)")
    time=$(date '+%d-%m-%y-%H_%M_%S')
    title="[$time] 	$url 	$f"
    
    echo
    echo $url
    echo
    echo "$title" >> "$HOME/.scripts/paste_hist.txt"
    
    links+=$url

done

echo -e "${links[@]}" #| sed 's/ /\n/g'
nohup $browser --new-tab "${links[@]}" &> /tmp/pastebin.out &!
