#!/usr/bin/env sh
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
conda activate bdfr
# <<< conda initialize <<<

dir="/run/media/ellio/T7/bdfr/fav"
process=$1
process_count=5
i=0

#Ghetto Multiprocessing 
#List of All Subreddits to update
subreddits=$(ls ${dir})
#Subreddit Math to Split into Two Groups
total_subreddit_count=$(echo "$subreddits" | wc -l)
array_groups=$(bc <<<$total_subreddit_count/$process_count)
#Split the List of All Subreddits Into Thirds
subreddit_array=($(xargs -n $array_groups <<<$subreddits | tr ' ' ','))

mainCMD(){
    subs=$(echo ${subreddit_array[$process]})
     
    #Run BDFR
    echo 
    echo "-->>> $subs -->>>"
    echo    
    python3 -m bdfr clone $dir \
        -s "$subs" \
        -t month \
        -S top \
        --file-scheme '{POSTID}'\
        --search-existing \
        --no-dupes
    echo
    echo "<<<-- $subs <<<--"
    echo
}

if [[ "$1" = "--all" ]]; then
    
    for k in "${subreddit_array[@]}";
    do
        nohup kitty -e sh -c "redhot-update $i" &
        ((i++))
    done

else

    mainCMD 

fi
