#!/usr/bin/env sh
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda/bin:$PATH"
    fi
fi
unset __conda_setup
conda activate bdfr
# <<< conda initialize <<<

dir="/mnt/PSSD_Storage/bdfr/fav"
process=$1

mainCMD(){
    #Ghetto Multiprocessing 
    #List of All Subreddits to update
    subreddits=$(ls ${dir})
    #Subreddit Math to Split into Two Groups
    total_subreddit_count=$(echo "$subreddits" | wc -l)
    one_third_of_subreddit_count=$(bc <<<$total_subreddit_count/3)
    #Split the List of All Subreddits Into Thirds
    subreddit_array=($(xargs -n $one_third_of_subreddit_count <<<$subreddits | tr ' ' ','))
    subs=$(echo ${subreddit_array[$process]})
     
    #Run BDFR
    echo 
    echo "-->>> $subs -->>>"
    echo    
    sudo python3 -m bdfr clone $dir \
        -s "$subs" \
        -t month \
        -S top \
        --file-scheme '{POSTID}'\
        --search-existing \
        --no-dupes
    echo
    echo "<<<-- $subs <<<--"
    echo
}

updateJSON(){
    dirs=($(ls /mnt/PSSD_Storage/bdfr/fav | sed '/nohup.out/d'))
    for d in "${dirs[@]}"; 
    do  
        echo "title,score,date,id" > "${HOME}"/"$d"_posts.csv
        for f in /mnt/PSSD_Storage/bdfr/fav/$d/*.json;
        do 
                cat $f | jq ".title, .score, .created_utc" | sd '\n' ','
                echo "/mnt/PSSD_Storage/bdfr/fav/$d/$(cat $f | jq ".id" | sd '"' '').mp4"
        done | tee -a "${HOME}"/"$d"_posts.csv
    done
    sudo mv "${HOME}"/*_posts.csv /mnt/PSSD_Storage/bdfr
}

if [[ "$1" = "--all" ]]; then
    kitty -e sh -c "redhot-update 0" &
    kitty -e sh -c "redhot-update 1" &
    kitty -e sh -c "redhot-update 2"
elif [[ "$1" = "-j" ]]; then
    updateJSON
else
    mainCMD 
fi
