#!/bin/sh

#eval $(slop -f "size=%wx%h pos=0+%x scale=%x")
file="output_$(date +%Y%m%d_%H%M%S).mp4"    

slop=$(slop -f "%x %y %w %h %g %i") || exit 1
read -r X Y W H G ID < <(echo $slop)

record_screen(){    
    ffmpeg -video_size "$W"x"$H" \
    -framerate 30 \
    -f x11grab \
    -i :0.0+$X,$Y \
    -c:v libx264rgb \
    -crf 0 \
    -preset ultrafast \
    "$file"
}

convert_to_gif(){
    ## TimeStamp
    tfn=$(date +%Y%m%d_%H%M%S)
    ## Output File Name
    output="output_$tfn.gif"
    
    ## Options
    
    echo "Start: "
    read start
    echo "Duration: "
    read duration
    echo "fps: "
    read fps
    
    ## Video to GIF
    ffmpeg \
        -ss $start \
        -t $duration \
        -i $file \
        -filter_complex \
        "[0:v] \
        fps=$fps,\
        scale=-1:$Y,\
        split [a][b];[a] palettegen [p];[b][p] paletteuse" \
        $output
    
    ## Play
    mpv $output
}

record_screen
convert_to_gif
