#!/usr/bin/env sh

tmpmail -g
site=$1
email=$(tmpmail | grep -oE "Inbox.*\.(com|net)" | cut -d ' ' -f3)
pass=$(pass generate temp/$site/$email 12)

GetMail(){
    LatestMail(){
        tmpmail | grep -oe "^[0-9].*[0-9]" | cut -d ' ' -f1 | head -n1
    }

    while [[ $(LatestMail) -lt "1" ]];
    do  
        echo
        echo "$(date "+%H:%M:%S %p"): No Recent mail for $email"
        echo
        echo "Username: $email"
        echo "Password: $(pass temp/$site/$email)"
        echo     
        LatestMail
        sleep 10s
    done

    tmpmail -b firefox -r
}

GetMail
