#!/bin/sh

files=($(fd . --extension="mp4"))

for video in "${files[@]}";
do
    output="$(basename $video ".mp4")" 
    ffmpeg -i $video -codec libx264 -crf 20 -pix_fmt yuv420p "compressed_$output.mp4"
done
