#!/bin/sh

#-geometry 95x48

if [[ $1 = "-main" ]]; then
urxvtc -name "vim" -title "vim" \
-e sh -c "sleep .3s; vim -S ~/.vim/sessions/main.vim"

elif [[ $1 = "-notes" ]]; then
urxvtc -name "notes" -title "notes" \
-e sh -c "vim -S ~/.vim/sessions/notes.vim"

elif [[ $1 = "-start-page" ]]; then
urxvtc -e sh -c "vim -S ~/.vim/sessions/start-page.vim"

elif [[ $1 = "-kitty" ]]; then
kitty -o="initial_window_width 1017" -o="initial_window_height 1162" \
 --name "vim" --title "vim"  -e sh -c \
"vim -S ~/.vim/sessions/main.vim"

elif [[ $1 = "-kitty2" ]]; then
kitty --name "vim2" --title "vim2" -e sh -c \
"vim -S ~/.vim/sessions/main.vim"
else
echo "Options: -main -notes -start-page"

fi
