# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 5000

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    family: canele

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    family: canele

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    family: canele

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    family: canele

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 8.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 1
    y: 1

window:
  opacity: 1.0
  padding:
    x: 15
    y: 15
# Colors
colors:
# Default colors
  primary:
    background: '#1a1b26'
    foreground: '#a9b1d6'
    
  # Normal colors
  normal:
    black:   '#282c34'
    red:     '#f7768e'
    green:   '#73daca'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'
    
  # Bright colors
  bright:
    black:   '#414868'
    red:     '#f7768e'
    green:   '#73daca'
    yellow:  '#e0af68'
    blue:    '#7aa2f7'
    magenta: '#bb9af7'
    cyan:    '#7dcfff'
    white:   '#c0caf5'
