#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.local/bin/eww -c $HOME/.config/eww/bar"
## Open widgets 
run_eww() {
	${EWW} open-many \
        bar
}

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	#sleep 1
fi

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww && bspc config -m HDMI-0 top_padding 49
else
	${EWW} close-all && killall eww
	rm "$FILE" 
    bspc config -m HDMI-0 top_padding 0
fi
