#!/bin/sh
if [[ $1 = "-ascii" ]]; then
urxvtc -name "neofetch-ascii" -title "neofetch-ascii" -e sh -c \
'neofetch --ascii "$(figlet -f /home/ellio/.fonts/misc/figlet/alpha.flf T)"; \
zsh'

elif [[ $1 = "-pic" ]]; then
urxvtc -name "neofetch-pic" -title "neofetch-pic" -e sh -c \
"neofetch --w3m ~/.config/neofetch/arch.png --loop; \
zsh"

elif [[ $1 = "-wal" ]]; then
urxvtc -name "neofetch" -title "neofetch" -e sh -c \
"neofetch --loop; \
zsh"

fi
