#!/bin/sh
if [[ $1 = "-2" ]]; then
urxvtc -name "tty-clock2" -title "tty-clock2" -e sh -c "tty-clock -c -t -C 7 -b"
else
urxvtc -name "tty-clock" -title "tty-clock" -e sh -c "tty-clock -c -t -C 7 -b;zsh"
fi
