#!/bin/sh

ip () {
echo $(ifconfig | rg -A 5 proton0 | rg "inet " | sd "netmask.*" "" | sd "inet" "" | sd " " "")
}

case $1 in
    " ")
        echo "-clean"
        echo "-init"
    ;;
    
    -clean)
        kubectl drain ellio-systemproductname --delete-emptydir-data --force --ignore-daemonsets; \
        sudo kubeadm reset; \
        sudo rm -rf /etc/cni/net.d; \
        rm /home/ellio/.kube/config; \
        docker container stop $(docker container ls -aq); docker container rm $(docker container ls -aq) ; \
        sudo iptables -F && sudo iptables -t nat -F && sudo iptables -t mangle -F && sudo iptables -X
        sudo systemctl restart kubelet; sleep 5s; \
        sudo systemctl restart docker; sleep 5s; \
        sudo systemctl stop kubepods.slice; \
        sudo systemctl daemon-reload; \
        sudo iptables --list; sleep 5s; \
    ;;
    
    -init)
        sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --control-plane-endpoint $(echo $(ip)):6443 --upload-certs ;\
        mkdir -p $HOME/.kube ;\
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config ;\
        sudo chown $(id -u):$(id -g) $HOME/.kube/config ;\
        export kubever=$(kubectl version | base64 | tr -d '\n') ;\
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"; \
        kubectl apply -f "https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml"
    ;;
esac
