#!/bin/sh

############
#   SPOT   #
############
if [[ $1 = "-spot" ]]; then
bspc node @^2:^7:/ -i
bspc node @^2:^7:/ -p east -i
bspc node @^2:^7:/2 -o 0.9 -p south -i

bspc rule -a URxvt:spot -o node=@^2:^7:/1 marked=on
bspc rule -a kitty:vis -o node=@^2:^7:/2/1 marked=on
bspc rule -a URxvt:lofi -o node=@^2:^7:/2/2 marked=on

urxvtc -geometry 100x100 -name "spot" -title "spot" -e sh -c "spt;zsh" &
visualizer &
urxvtc -name "lofi" -title "lofi" -e sh -c 'mpv --x11-name="lofi" --title="lofi" ~/Music/ --mute=no --no-video;zsh'

###############
#   NCMPCPP   #
###############
else
bspc node @^2:^8:/ -i 
bspc node @^2:^8:/ -p south -i

bspc rule -a kitty:music -o node=@^2:^8:/1 marked=on
bspc rule -a kitty:vis -o node=@^2:^8:/2 marked=on

kitty --name "music" --title "music" -e sh -c "~/.ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug" &
visualizer
fi
