#!/bin/sh

col=$(cat ~/.config/kitty/layout-case-color)
while bspc node 'any.leaf.!window' -k; do :; done;
while bspc node 'any.marked.!local' -c; do :; done;

##########
#   PS   #
##########
if [[ $1 = "-ps" ]]; then
##INSERT RECEPTACLES
bspc node @^1:^1:/ -i 
bspc node @^1:^1:/ -o .52 -p east -i
bspc node @^1:^1:/1 -o .498 -p south -i
##ADD RULES
bspc rule -a mpv:ps -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2 marked=on focus=off
bspc rule -a kitty:tty-clock -o node=@^1:^1:/1/2 marked=on focus=off
##LAUNCH APPS
mpv --x11-name="ps" --title="ps" ~/Pictures/gifs/ps.GIF & 
kitty --name "gotop" --title "gotop" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "gotop" &
kitty --name "tty-clock" --title "tty-clock" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "tty-clock -c -t -C 7 -b" &
sleep .5s; bspc desktop --focus ^2:focused

##############
#   NARUTO   #
##############
elif [[ $1 = "-naruto" ]]; then
##INSERT RECEPTACLES
bspc node @^1:^1:/ -i
bspc node @^1:^1:/ -o 0.52 -p east -i
bspc node @^1:^1:/2 -o 0.34 -p south -i
##ADD RULES
bspc rule -a kitty:tty-clock -o node=@^1:^1:/1 marked=on focus=off
bspc rule -a mpv:naruto -o node=@^1:^1:/2/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2/2 marked=on focus=off
##LAUNCH APPS
kitty --name "tty-clock" --title "tty-clock" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "tty-clock -c -t -C 7 -b" &
mpv --x11-name="naruto" --title="naruto" ~/Videos/N.mp4 &
kitty --name "gotop" --title "gotop" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "gotop" &
sleep .5s; bspc desktop --focus ^2:focused

############
#   MOB    #
############
elif [[ $1 = "-mob" ]]; then
##INSERT RECEPTACLES
bspc node @^1:^1:/ -i
bspc node @^1:^1:/ -o 0.4575 -p east -i
bspc node @^1:^1:/1 -o 0.617656 -p south -i 
bspc node @^1:^1:/2 -o 0.383281 -p south -i

## ADD RULES
bspc rule -a kitty:vis-case -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a kitty:tty-clock -o node=@^1:^1:/1/2 marked=on focus=off
bspc rule -a mpv:mob -o node=@^1:^1:/2/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2/2 marked=on focus=off

## LAUNCH COMMANDS 
kitty --name "vis-case" --title "vis-case" \
-o include="~/.config/kitty/$col-kitty.conf" -e sh -c \
"kitty @set-font-size 1; vis" &
kitty --name "tty-clock" --title "tty-clock" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "tty-clock -c -t -C 7 -b" &
mpv --x11-name="mob" --title="mob" ~/Videos/mob.mkv &
kitty --name "gotop" --title "gotop" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "gotop" &
sleep .5s; bspc desktop --focus ^2:focused

############
#   DARK   #
#############
elif [[ $1 = "-dark" ]]; then
## INSERT RECEPTACLES
bspc node @^1:^1:/ -i 
bspc node @^1:^1:/ -o .52 -p east -i
bspc node @^1:^1:/1 -o .498 -p south -i
## ADD RULES
bspc rule -a mpv:walking -o node=@^1:^1:/1/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2 marked=on focus=off
bspc rule -a kitty:tty-clock -o node=@^1:^1:/1/2 marked=on focus=off
##LAUNCH APPS
mpv --x11-name="walking" --title="walking" ~/Pictures/gifs/walking.GIF &
kitty --name "gotop" --title "gotop" -o include="~/.config/kitty/black-kitty.conf" -e sh -c "gotop" &
kitty --name "tty-clock" --title "tty-clock" -o include="~/.config/kitty/black-kitty.conf" -e sh -c "tty-clock -c -t -C 7 -b" &
sleep .5s; bspc desktop --focus ^2:focused

###############
#   MINIMAL   #
###############
else
##INSERT RECEPTACLES
bspc node @^1:^1:/ -i 
bspc node @^1:^1:/ -o 0.52 -p east -i
##ADD RULES
bspc rule -a kitty:tty-clock -o node=@^1:^1:/1 marked=on focus=off
bspc rule -a kitty:gotop -o node=@^1:^1:/2 marked=on focus=off
##LAUNCH APPS
kitty --name "tty-clock" --title "tty-clock" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "tty-clock -c -t -C 7 -b" &
kitty --name "gotop" --title "gotop" -o include="~/.config/kitty/$col-kitty.conf" -e sh -c "gotop" &
sleep .5s; bspc desktop --focus ^2:focused
fi
