#!/bin/sh

if [[ $1 = "-all" ]]; then
#INSERT RECEPTACLES
bspc node @^1:/ -i 
bspc node @^1:/ -p east -i 
bspc node @2:/ -i 
bspc node @2:/ -o 0.602267 -p east -i
bspc node @2:/2 -o 0.421183 -p east -i
#ADD RULES
bspc rule -a URxvt:tty-clock -o node=@^1:^1:/1 state=pseudo_tiled
bspc rule -a URxvt:gotop -o node=@^1:^1:/2 state=pseudo_tiled
bspc rule -a kitty:ranger -o node=@^2:^1:/1
bspc rule -a mpv:gifs -o node=@^2:^1:/2/1
bspc rule -a URxvt:gotop -o node=@^2:^1:/2/2/
#LAUNCH APPS
clock &
gotop-pos &
launch 

elif [[ $1 = "-left" ]]; then
#INSERT RECEPTACLES
bspc node @^1:/ -i 
bspc node @^1:/ -p east -i 
#ADD RULES
bspc rule -a URxvt:tty-clock -o node=@^1:^1:/1 state=pseudo_tiled
bspc rule -a mpv:gl -o node=@^1:^1:/2 state=pseudo_tiled
#LAUNCH APPS
clock &
mpv /home/ellio/Pictures/gifs

else
#INSERT RECEPTACLES
bspc node @2:/ -i 
bspc node @2:/ -o 0.602267 -p east -i
bspc node @2:/2 -o 0.421183 -p east -i
#ADD RULES
bspc rule -a kitty:ranger -o node=@^2:^1:/1
bspc rule -a mpv:gifs -o node=@^2:^1:/2/1
bspc rule -a URxvt:gotop -o node=@^2:^1:/2/2/
#LAUNCH APPS
launch
fi
