#!/bin/sh

###################
#   RIGHT-TITAN   #
###################

if [[ $1 = "--titan" ]]; then

##INSERT RECEPTACLES
bspc node @^2:^1:/ -i 
bspc node @^2:^1:/ -o 0.438895 -p east -i
bspc node @^2:^1:/1 -p south -i
bspc node @^2:^1:/2 -o 0.298829 -p east -i
bspc node @^2:^1:/2/2 -o 0.7 -p south -i
bspc node @^2:^1:/2/2/2 -o .52 -p east -i
bspc node @^2:^1:/2/2/2/1 -o .52 -p south -i
bspc node @^2:^1:/2/2/2/2 -o .52 -p south -i

##ADD RULES
bspc rule -a URxvt:ranger -o node=@^2:^1:/1/1
bspc rule -a URxvt:htop -o node=@^2:^1:/1/2
bspc rule -a mpv:gifs -o node=@^2:^1:/2/1
bspc rule -a URxvt:vim -o node=@^2:^1:/2/2/1
bspc rule -a URxvt:TANK -o node=@^2:^1:/2/2/2/1/1
bspc rule -a URxvt:matrix -o node=@^2:^1:/2/2/2/1/2
bspc rule -a URxvt:pro -o node=@^2:^1:/2/2/2/2/1
bspc rule -a URxvt:tty-clock2 -o node=@^2:^1:/2/2/2/2/2

##LAUNCH APPS
titan &
sleep 3.4s; urxvtc -name "ranger" -title "ranger" -e ranger --selectfile=Pictures/sbpt.png &
sleep .7s; gotop-pos -h &
sleep .5s; mpv --x11-name="gifs" --title="gifs" ~/Videos/1.mov &
sleep .5s; vim-sessions -main
sleep .7s; message &
sleep 2.4s; matrix &
sleep 1s; pro -f &
sleep .8s; clock -2

############################
#   RIGHT 2 (PC + nvtop)   #
############################

elif [[ $1 = "--right-2" ]]; then

##INSERT RECEPTACLES
bspc node @^2:^1:/ -i 
bspc node @^2:^1:/ -o 0.438895 -p east -i
bspc node @^2:^1:/1 -p south -i
bspc node @^2:^1:/1/1 -o 0.718807 -p east -i
bspc node @^2:^1:/1/1/1 -o 0.52 -p south -i
bspc node @^2:^1:/2 -o 0.298829 -p east -i
bspc node @^2:^1:/2/2 -o 0.718807 -p south -i
bspc node @^2:^1:/2/2/2 -o .52 -p east -i
bspc node @^2:^1:/2/2/2/1 -o .52 -p south -i
bspc node @^2:^1:/2/2/2/2 -o .52 -p south -i


##ADD RULES
bspc rule -a URxvt:ranger -o node=@^2:^1:/1/1/1/1
bspc rule -a URxvt:nvtop -o node=@^2:^1:/1/1/1/2
bspc rule -a mpv:pc -o node=@^2:^1:/1/1/2
bspc rule -a URxvt:htop -o node=@^2:^1:/1/2
bspc rule -a mpv:gifs -o node=@^2:^1:/2/1
bspc rule -a URxvt:vim -o node=@^2:^1:/2/2/1
bspc rule -a URxvt:TANK -o node=@^2:^1:/2/2/2/1/1
bspc rule -a URxvt:matrix -o node=@^2:^1:/2/2/2/1/2
bspc rule -a URxvt:pro -o node=@^2:^1:/2/2/2/2/1
bspc rule -a URxvt:tty-clock2 -o node=@^2:^1:/2/2/2/2/2

##LAUNCH APPS
urxvtc -name "ranger" -title "ranger" -e ranger --selectfile=Pictures/sbpt.png &
mpv --x11-name="pc" --title="pc" ~/Videos/pc.mp4 &
nvtop-pos &
gotop-pos -h &
mpv --x11-name="gifs" --title="gifs" ~/Videos/1.mov &
vim-sessions -main
sleep .3s; message &
matrix &
pro -f &
clock -2

#############
#   RIGHT   #
#############
else

##INSERT RECEPTACLES
bspc node @^2:^1:/ -i 
bspc node @^2:^1:/ -o 0.438895 -p east -i
bspc node @^2:^1:/1 -p south -i
bspc node @^2:^1:/2 -o 0.298829 -p east -i
bspc node @^2:^1:/2/2 -o 0.7 -p south -i
bspc node @^2:^1:/2/2/2 -o .52 -p east -i
bspc node @^2:^1:/2/2/2/1 -o .52 -p south -i
bspc node @^2:^1:/2/2/2/2 -o .52 -p south -i

##ADD RULES
bspc rule -a URxvt:ranger -o node=@^2:^1:/1/1
bspc rule -a URxvt:htop -o node=@^2:^1:/1/2
bspc rule -a mpv:gifs -o node=@^2:^1:/2/1
bspc rule -a URxvt:vim -o node=@^2:^1:/2/2/1
bspc rule -a URxvt:TANK -o node=@^2:^1:/2/2/2/1/1
bspc rule -a URxvt:matrix -o node=@^2:^1:/2/2/2/1/2
bspc rule -a URxvt:pro -o node=@^2:^1:/2/2/2/2/1
bspc rule -a URxvt:tty-clock2 -o node=@^2:^1:/2/2/2/2/2

##LAUNCH APPS
urxvtc -name "ranger" -title "ranger" -e ranger --selectfile=Pictures/sbpt.png &
gotop-pos -h &
mpv --x11-name="gifs" --title="gifs" ~/Videos/1.mov &
vim-sessions -main
sleep .3s; message &
matrix &
urxvtc -name "pro" -title "pro" -e sh -c "sudo protonvpn c -f;zsh" &
clock -2
fi
