#!/bin/sh

## move to desktop & close windows
bspc desktop -f ^2:^7;
while bspc node 'any.leaf.local' -c; do :; done;
while bspc node 'any.leaf.!window.local' -k; do :; done;

##INSERT RECEPTACLES
bspc node @^2:^7:/ -i
bspc node @^2:^7:/ -o 0.52 -p east -i
bspc node @^2:^7:/1 -o 0.52 -p south -i
bspc node @^2:^7:/2 -o 0.9 -p south -i

##ADD RULES
bspc rule -a URxvt:spot -o node=@^2:^7:/1/1
bspc rule -a kitty:music -o node=@^2:^7:/1/2
bspc rule -a URxvt:vis -o node=@^2:^7:/2/1
bspc rule -a URxvt:lofi -o node=@^2:^7:/2/2

##LAUNCH APPS
urxvtc -geometry 100x100 -name "spot" -title "spot" -e sh -c "spt;zsh" &
kitty --name "music" --title "music" -e sh -c "~/.ncmpcpp/ncmpcpp-ueberzug/ncmpcpp-ueberzug" &
visualizer &
urxvtc -name "lofi" -title "lofi" -e sh -c 'mpv --x11-name="lofi" --title="lofi" ~/Music/ --mute=no --no-video;zsh'
