#!/bin/sh
## move to desktop and clear windows
bspc desktop -f ^2:^5; while bspc node 'any.leaf.local' -c; do :; done;
## insert receptacles
bspc node @^2:^5:/ -i
bspc node @^2:^5:/ -o 0.206628 -p east -i
bspc node @^2:^5:/2 -o 0.25975 -p east -i
## add rules
bspc rule -a mpv:alexa -o node=@^2:^5:/1 marked=on
bspc rule -a mpv:h -o node=@^2:^5:/2/1 marked=on
bspc rule -a \*:\* -o node=@^2:^5:/2/2
## launch apps
mpv --x11-name="alexa" --title="alexa" ~/Videos/h/ap/ --video-zoom=0.2 &
mpv --x11-name="h" --title="h" ~/Videos/h/b/ --video-zoom=0.2
