#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color12"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color2"
