#!/bin/sh
if [[ $1 = "-s" ]]; then
urxvtc -name "ranger" -title "ranger" -geometry 74x20 -e sh -c "~/.scripts/ranger/ranger.py;zsh"
elif [[ $1 = "-k" ]]; then
kitty --name "ranger" --title "ranger" -e sh -c "~/.scripts/ranger/ranger.py -r ~/.config/ranger/kitty;zsh"
else
urxvtc -name "ranger" -title "ranger" -geometry 74x25 -e "ranger"
fi
