#!/bin/sh
if [[ $1 = "-s" ]]; then
urxvtc -name "ranger" -title "ranger" -geometry 74x20 -e sh -c "~/.scripts/ranger/ranger.py"
elif [[ $1 = "-k" ]]; then
kitty --name "ranger" --title "ranger" -e sh -c "ranger --cmd='set preview_images_method ueberzug' --cmd='default_linemode devicons2' --cmd='set draw_borders false'"
elif [[ $1 = "-ks" ]]; then
kitty --name "ranger" --title "ranger" -e sh -c "~/.scripts/ranger/ranger.py --cmd='set preview_images_method ueberzug' --cmd='default_linemode devicons2' --cmd='set draw_borders false'"
else
urxvtc -name "ranger" -title "ranger" -geometry 74x25 -e "ranger"
fi
