#!/bin/sh
bspc node @^2:^7:/ -i
bspc node @^2:^7:/ -p east -i
bspc node @^2:^7:/2 -o 0.9 -p south -i

bspc rule -a URxvt:spot -o node=@^2:^7:/1
bspc rule -a kitty:vis -o node=@^2:^7:/2/1
bspc rule -a URxvt:lofi -o node=@^2:^7:/2/2

urxvtc -geometry 100x100 -name "spot" -title "spot" -e sh -c "spt;zsh" &
visualizer &
urxvtc -name "lofi" -title "lofi" -e sh -c 'mpv --x11-name="lofi" --title="lofi" ~/Music/1am.mp3 --mute=no --no-video;zsh'
