#!/bin/sh

tsd=$(sudo timeshift --list | grep -m 2 -o "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9]-[0-9][0-9]-[0-9][0-9]" | tail -1)
figlet -f ~/.fonts/misc/figlet/3D-ASCII.flf 'Back-Up'; \
sudo timeshift --list; \
sudo timeshift --delete --snapshot $tsd; \
sudo timeshift --create --comments "house-keeping"; \
zsh
