#!/bin/sh

if [[ $1 = "-pipes-v" ]]; then
kitty --name "pipes-vertical" --title "pipes-vertical" \
-e sh -c \
"sleep .3s; pipes-vertical"

elif [[ $1 = "-pipes-d" ]]; then
kitty --name "pipes-diagonal" --title "pipes-diagonal" \
-e sh -c \
"sleep .3s; pipes-diagonal"

elif [[ $1 = "-matrix" ]]; then
. "${HOME}/.cache/wal/colors.sh"
urxvtc -name "matrix" -title "matrix" -bg "$background" -bd "$background" \
-e sh -c \
"sleep .2s; cmatrix -u 7"

else
echo "options: -pipes-v | -pipeps-d | -matrix"

fi
