#!/bin/sh
if [[ $1 = "-s" ]]; then
fcs=$(cat /home/ellio/Downloads/iTerm2-Color-Schemes/cs | tail -n 1)
echo $fcs >> /home/ellio/Downloads/iTerm2-Color-Schemes/f_cs

else
i=0    
## VARIABLES ##
while [[ $i -ge 0 ]] 
do
random_scheme=$(ls -d /home/ellio/Downloads/iTerm2-Color-Schemes/alacritty/* | shuf -n 1)
dir=$(echo "$random_scheme")
cs_name=$(echo $random_scheme | grep -o "alacritty/.*" | cut -d "/" -f2 | rev | cut -c 5- | rev)


## PRINT CS NAME ##
echo $cs_name >> ~/Downloads/iTerm2-Color-Schemes/cs ; \

## CLEAR EXISTING ##
sed -i '/^# Colors/,$d' /home/ellio/.config/alacritty/alacritty.yml; \
sed -i '/include/d' ~/.config/kitty/kitty.conf; \

## ALACRITTY ##
cat $dir >> /home/ellio/.config/alacritty/alacritty.yml; \

## KITTY ##
echo "include ~/Downloads/iTerm2-Color-Schemes/kitty/$cs_name.conf" >> ~/.config/kitty/kitty.conf; \

## URXVT ##
sed -i '/^\*.color0/,/^\*color15/d' ~/.Xresources2; \
sed -i '/*.cursorColor/d' ~/.Xresources2; \
sed -i '/*.foreground/d' ~/.Xresources2; sed -i '/*.background/d' ~/.Xresources2; \
#sed -i '/^\*.foreground/,$d' ~/.Xresources2; \

cat ~/Downloads/iTerm2-Color-Schemes/Xresources/$cs_name >> ~/.Xresources2; \
sed -i 's/*.foreground:  /*.foreground:[90]/g' ~/.Xresources2; \
sed -i 's/*.background:  /*.background:[90]/g' ~/.Xresources2; \

xrdb ~/.Xresources2

echo "~/Downloads/iTerm2-Color-Schemes/Xresources/$cs_name"
sleep 2.5s;
done
fi
