#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "#A8A8A6"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"
