#!/bin/sh

##set variables
. "${HOME}/.cache/wal/colors.sh"; \
alpha=$(cat ~/.cache/wal/colors.json | head -n 3 | tail -n 1 | tail -c 5 | cut -c1-2)

#Delete old color & opacity
sed -i '/URxvt\*background:/d' ~/.Xresources; \
sed -i '/URxvt\*borderColor:/d' ~/.Xresources; \

#insert new
echo "URxvt*background:[$alpha]$background" >> ~/.Xresources; \
echo "URxvt*borderColor:[$alpha]$background" >> ~/.Xresources; \

xrdb ~/.Xresources
