#!/bin/sh

alpha=$(cat ${HOME}/.cache/wal/colors.Xresources | grep -o -e "\[.*\]" | head -n1 | sed 's/\[\|\]//g')

alacritty_fix() {
    ##set variables 
    . "${HOME}/.cache/wal/colors.sh"; \
    converted=$(bc <<<"$alpha*0.01" | head -c 3)
    if [[ $alpha -gt "99" ]]; then
        t=$converted
    else
        t="0$converted"
    fi
    ##remove previous colors and alpha
    sed -i '/^window:/,$d' ~/.config/alacritty/alacritty.yml; \
    
    ##output
    
    echo \
    "window:
  opacity: $t
  padding:
    x: 15
    y: 15
# Colors
colors:
# Default colors
  primary:
    background: '$background'
    foreground: '$foreground'
    
  # Normal colors
  normal:
    black:   '$color0'
    red:     '$color1'
    green:   '$color2'
    yellow:  '$color3'
    blue:    '$color4'
    magenta: '$color5'
    cyan:    '$color6'
    white:   '$color7'
    
  # Bright colors
  bright:
    black:   '$color8'
    red:     '$color9'
    green:   '$color10'
    yellow:  '$color11'
    blue:    '$color12'
    magenta: '$color13'
    cyan:    '$color14'
    white:   '$color15'" >> ~/.config/alacritty/alacritty.yml
}

kitty_fix() {
    sed -i '/^background_opacity/d' ~/.config/kitty/kitty.conf

    if [[ $alpha -gt "99" ]]; then
        a=$alpha
    else
        a="0.$alpha"
    fi

    echo "background_opacity $a" >> ~/.config/kitty/kitty.conf
    
    sed -i '/^include/d' ~/.config/kitty/kitty.conf
    echo "include ~/.cache/wal/colors-kitty.conf" >> ~/.config//kitty/kitty.conf
}

URxvt_fix() {
    sed -i '/^! X/,$d' ~/.Xresources
    cat ~/.cache/wal/colors.Xresources >> ~/.Xresources
    xrdb ~/.Xresources
}    

bspwm_border_color(){
    . "${HOME}/.cache/wal/colors.sh"
    bspc config normal_border_color "$color0"
    bspc config active_border_color "$color0"
    bspc config focused_border_color "$color4"
    bspc config presel_feedback_color "$color1"
    bspc config border_width 2
}

case $1 in
    "")
    alacritty_fix &
    kitty_fix &
    URxvt_fix
    ;;
    -b)
    alacritty_fix &
    kitty_fix &
    URxvt_fix &
    bspwm_border_color    
    ;;
esac
